### ISSUE TITLE
doc(chapter01/sanhyo/Readme.md): 리드미 오타

### ISSUE THREAD

**Issue by HM4725** [HM4725/ObjectStudy#1]
## 문제 발견
1. [제목 + 엔터](https://github.com/HM4725/ObjectStudy/tree/master/chapter01/sanghyo#1-%EA%B0%9D%EC%B2%B4-%EC%84%A4%EA%B3%84-)

엔터가 있어서 헤더 밑줄이 이상하게 보입니다.

> <img width="1023" alt="issue01" src="https://github.com/HM4725/ObjectStudy/assets/32367805/e428de16-d5c3-4652-bf1f-7836fcd8d9df">

2. [예시 코드 오타](https://github.com/HM4725/ObjectStudy/tree/master/chapter01/sanghyo#%EA%B8%B0%EC%A1%B4-%EC%B1%85-%EC%BD%94%EB%93%9C)

> <img width="807" alt="issue01-02" src="https://github.com/HM4725/ObjectStudy/assets/32367805/179c037d-49b6-4c6f-9520-b1a9fd654e77">

## 해결 제안
1. `<br />` 태그 제거
3. `class Teater` -> `class Theater`

**Comment by SH0123** [comment]
땡베감 @HM4725
